version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users

  user-service:
    build: .
    environment:
      DB_HOST: db
    depends_on:
      - db